"""
Admittance is inverse impedance
===============================

*Admittance, or complex conductance*, is a physical quantity measuring the
ability of a circuit or device to conduct electrical current.
"""

from sympy import (Eq, solve)
from symplyphysics import (units, Quantity, SymbolNew, validate_input, validate_output)

admittance = SymbolNew("Y", units.conductance)
"""
Admittance of the object.
"""

impedance = SymbolNew("Z", units.impedance)
"""
:doc:`Impedance <definitions.impedance_is_resistance_and_reactance>` of the object.
"""

# TODO: use autogenerated representation, but fix (1 / Z) code representation before

definition = Eq(admittance, 1 / impedance)
r"""
:code:`Y = 1 / Z`

:laws:latex::
"""


@validate_input(impedance_=impedance)
@validate_output(admittance)
def calculate_admittance(impedance_: Quantity) -> Quantity:
    solved = solve(definition, admittance, dict=True)[0][admittance]
    result_expr = solved.subs({impedance: impedance_})
    return Quantity(result_expr)
