"""
Physical symbols
================

Symbols represent physical quantities, units, mathematical operations and relationships.
"""

from .basic import *
from .chemistry import *
from .classical_mechanics import *
from .electrodynamics import *
from .optics import *
from .relativistic_mechanics import *
from .thermodynamics import *
from .astronomy import *
from .quantum_mechanics import *
from .nuclear import *

__all__ = [
    # basic
    "time",
    "period",
    "mass",
    "work",
    "energy_density",
    "energy",
    "power",
    "radius_of_curvature",
    "density",
    "intensity",
    "positive_number",
    "number_density",
    "particle_count",
    "angle",
    "linear_density",
    "whole_number",
    "spectral_energy_density",
    "molar_mass",
    "probability",
    "whole_number",
    "any_quantity",
    "fractional_change",
    "exponential_decay_constant",
    "specific_energy",
    "nonnegative_number",
    "characteristic_length",
    "molar_volume",
    # chemistry,
    "mass_fraction",
    "amount_of_substance",
    "density_of_states",
    "band_gap",
    "work_function",
    "drift_velocity",
    "molar_concentration",
    "ionization_coefficient",
    "cross_section",
    "atomic_number",
    "valence",
    "equilibrium_constant",
    "electrochemical_equivalent",
    "mobility",
    "diffusion_coefficient",
    "mass_number",
    # classical mechanics
    "force",
    "speed",
    "acceleration",
    "euclidean_distance",
    "distance",
    "distance_to_origin",
    "distance_to_axis",
    "length",
    "area",
    "angular_speed",
    "angular_frequency",
    "angular_acceleration",
    "angular_distance",
    "angular_wavenumber",
    "wavelength",
    "damping_ratio",
    "volume",
    "impulse",
    "position",
    "phase_speed",
    "pressure",
    "thickness",
    "temporal_frequency",
    "sound_intensity_level",
    "rotational_inertia",
    "quality_factor",
    "momentum",
    "mechanical_energy",
    "kinetic_energy",
    "potential_energy",
    "mass_flow_rate",
    "stiffness",
    "compliance",
    "young_modulus",
    "phase_shift",
    "friction_coefficient",
    "height",
    "torque",
    "torsion_stiffness",
    "bulk_modulus",
    "poisson_ratio",
    "engineering_normal_strain",
    "deformation",
    "strain",
    "stress",
    "group_speed",
    "phase",
    "tension",
    "mach_number",
    "radius",
    "diffusion_coefficient",
    "dynamic_viscosity",
    "diffusion_flux",
    "degrees_of_freedom",
    "angular_momentum",
    "arc_length",
    "semimajor_axis",
    "semiminor_axis",
    "latitude",
    "longitude",
    "sector_speed",
    "kepler_constant",
    "diameter",
    "surface_tension",
    "orthogonal_distance",
    "dynamic_pressure",
    "mechanical_efficiency",
    "hydrostatic_pressure",
    "froude_number",
    "volumetric_flow_rate",
    "nusselt_number",
    "reynolds_number",
    "stress",
    "shear_stress",
    "flow_speed",
    # electrodynamics
    "admittance",
    "electrical_conductance",
    "susceptance",
    "electrical_impedance",
    "electromotive_force",
    "magnetic_flux",
    "absolute_permittivity",
    "relative_permittivity",
    "capacitance",
    "charge",
    "voltage",
    "current",
    "electrical_resistance",
    "electric_dipole_moment",
    "electric_field_strength",
    "surface_charge_density",
    "electric_flux",
    "magnetic_flux_density",
    "electric_potential",
    "power_factor",
    "electrical_resistivity",
    "inductance",
    "electric_time_constant",
    "electrical_reactance",
    "current_density",
    "relative_permeability",
    "emissivity",
    "magnetic_moment",
    "absolute_permeability",
    "electric_displacement",
    "attenuation_coefficient",
    "electrical_conductivity",
    "wave_impedance",
    "circuit_gain",
    "diode_constant",
    "volumetric_charge_density",
    "direct_permeability_coefficient",
    "attenuation",
    "surge_impedance",
    "reflection_coefficient",
    "standing_wave_ratio",
    "phase_constant",
    "propagation_constant",
    # optics
    "relative_refractive_index",
    "radiant_exitance",
    "radiant_flux",
    "focal_length",
    "optical_distance",
    "transparency_coefficient",
    "reflectance",
    "magnification",
    "optical_power",
    "angular_resolution",
    # relativistic mechanics
    "lorentz_factor",
    "spacetime_interval",
    "proper_time",
    "rest_mass",
    "proper_length",
    "relativistic_mass",
    # thermodynamics
    "temperature",
    "adiabatic_index",
    "heat_capacity",
    "thermal_expansion_coefficient",
    "thermodynamic_compressibility",
    "thermal_resistance",
    "thermal_conductivity",
    "thermal_insulance",
    "compressibility_factor",
    "partition_function",
    "boltzmann_factor",
    "entropy",
    "molar_heat_capacity",
    "chemical_potential",
    "gibbs_energy",
    "enthalpy",
    "helmholtz_free_energy",
    "internal_energy",
    "thermal_wavelength",
    "heat",
    "thermal_efficiency",
    "statistical_weight",
    "relative_humidity",
    "mean_free_path",
    "sutherland_constant",
    "prandtl_number",
    "grashof_number",
    "kinematic_viscosity",
    "thermal_diffusivity",
    "attractive_forces_parameter",
    "excluded_volume_parameter",
    "heat_transfer_coefficient",
    # astronomy
    "absolute_magnitude",
    "apparent_magnitude",
    "luminosity",
    "illuminance",
    "irradiance",
    "eccentricity",
    "zenith_angle",
    "declination",
    "altitude",
    # quantum mechanics
    "wave_function",
    "probability_density",
    # nuclear physics
    "geometric_buckling",
    "infinite_multiplication_factor",
    "multiplication_factor",
    "effective_multiplication_factor",
    "neutron_diffusion_area",
    "neutron_flux",
    "material_buckling",
    "fast_non_leakage_probability",
    "thermal_non_leakage_probability",
    "resonance_escape_probability",
    "fast_absorption_fission_probability",
    "thermal_absorption_fission_probability",
    "thermal_utilization_factor",
    "neutron_fermi_age",
    "thermal_fission_factor",
    "half_life",
    "neutron_diffusion_coefficient",
    "reproduction_factor",
]
