"""
Physical symbols
================

Symbols represent physical quantities, units, mathematical operations and relationships.
"""

from .basic import *
from .chemistry import *
from .classical_mechanics import *
from .electrodynamics import *
from .optics import *
from .relativistic_mechanics import *
from .thermodynamics import *

__all__ = [
    # basic
    "time",
    "period",
    "mass",
    "work",
    "energy_density",
    "energy",
    "power",
    "radius_of_curvature",
    "density",
    "intensity",
    "positive_number",
    "number_density",
    "particle_count",
    "angle",
    "linear_density",
    "whole_number",
    "spectral_energy_density",
    "molar_mass",
    "probability",
    "whole_number",
    "any_dimension",
    "fractional_change",
    # chemistry,
    "mass_fraction",
    "amount_of_substance",
    "density_of_states",
    "band_gap",
    "work_function",
    "drift_velocity",
    "molar_concentration",
    # classical mechanics
    "force",
    "speed",
    "acceleration",
    "distance",
    "distance_to_origin",
    "distance_to_axis",
    "length",
    "area",
    "angular_speed",
    "angular_frequency",
    "angular_acceleration",
    "angular_distance",
    "angular_wavenumber",
    "wavelength",
    "damping_ratio",
    "volume",
    "impulse",
    "position",
    "phase_speed",
    "pressure",
    "thickness",
    "temporal_frequency",
    "sound_intensity_level",
    "rotational_inertia",
    "quality_factor",
    "momentum",
    "mechanical_energy",
    "kinetic_energy",
    "potential_energy",
    "mass_flow_rate",
    "stiffness",
    "compliance",
    "young_modulus",
    "phase_shift",
    "friction_coefficient",
    "height",
    "torque",
    "torsion_stiffness",
    "bulk_modulus",
    "poisson_ratio",
    "engineering_normal_strain",
    "deformation",
    "strain",
    "stress",
    "group_speed",
    "phase",
    "tension",
    "mach_number",
    "radius",
    "diffusion_coefficient",
    "dynamic_viscosity",
    "diffusion_flux",
    "degrees_of_freedom",
    "angular_momentum",
    "arc_length",
    # electrodynamics
    "admittance",
    "electrical_conductance",
    "susceptance",
    "electrical_impedance",
    "electromotive_force",
    "magnetic_flux",
    "absolute_permittivity",
    "relative_permittivity",
    "capacitance",
    "charge",
    "voltage",
    "current",
    "electrical_resistance",
    "electric_dipole_moment",
    "electric_field_strength",
    "surface_charge_density",
    "electric_flux",
    "magnetic_flux_density",
    "electric_potential",
    "power_factor",
    "electrical_resistivity",
    "inductance",
    "electric_time_constant",
    "electrical_reactance",
    "current_density",
    "relative_permeability",
    "emissivity",
    "magnetic_moment",
    "absolute_permeability",
    # optics
    "relative_refractive_index",
    "radiant_exitance",
    "radiant_flux",
    "focal_length",
    # relativistic mechanics
    "lorentz_factor",
    # thermodynamics
    "temperature",
    "adiabatic_index",
    "heat_capacity",
    "thermal_expansion_coefficient",
    "thermodynamic_compressibility",
    "thermal_resistance",
    "thermal_conductivity",
    "thermal_insulance",
    "compressibility_factor",
    "partition_function",
    "boltzmann_factor",
    "entropy",
    "molar_heat_capacity",
    "chemical_potential",
    "gibbs_energy",
    "enthalpy",
    "helmholtz_free_energy",
    "internal_energy",
    "thermal_wavelength",
    "heat",
    "thermal_efficiency",
    "statistical_weight",
    "relative_humidity",
]
