name: Deploy

on:
  push:
    branches: ["deploy"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install symplyphysics
      run: pip install .[dev,plots]

    - name: Build docs
      run: |
        docs/build.py -s symplyphysics -o docs/generated -e core

    - name: Push changes
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SYMPLYPHYSICS_PAGES_PK }}
      with:
          # GitHub Action output files
          source-directory: html/
          destination-github-username: symplyphysics
          destination-repository-name: symplyphysics.github.io
          user-email: sam.and.tetris@gmail.com
          target-branch: "master"