"""
Maxwell's Equations
===================

**Maxwell's equations** are a set of coupled partial differential equations that describe how
electric and magnetic fields are generated by electric charges and currents.

**Links:**

#. `Wikipedia — Maxwell's equations <https://en.wikipedia.org/wiki/Maxwell%27s_equations>`__
"""
